### ISSUE TITLE
First run, first error (tdm64): gcc: fatal error: cannot execute 'cc1':

### ISSUE THREAD

**Issue by BoQsc** [jmeubank/tdm-distrib#1]
@jmeubank 
## Command Prompt
```
C:\Users\vaida\Desktop\gcc\bin>gcc hello.c
gcc: fatal error: cannot execute 'cc1': CreateProcess: No such file or directory
compilation terminated.
```
## hello.c
```
#include <stdio.h>
int main() {
   // printf() displays the string inside quotation
   printf("Hello, World!");
   return 0;
}
```

**Comment by jmeubank** [comment]
This type of output is common; please try some of the troubleshooting steps you'll find here:
https://lmgtfy.com/?q=gcc%3A+fatal+error%3A+cannot+execute+%27cc1%27%3A+CreateProcess%3A+No+such+file+or+directory

...and report back on what you've tried.

**Comment by jmeubank** [comment]
Closing as inactive.
