### ISSUE TITLE
windows default manifest

### ISSUE THREAD

**Issue by pjsr1980** [jmeubank/tdm-distrib#3]
Hello, do you have any solution for the topic discussed at this address: https://github.com/msys2/MSYS2-packages/issues/454

I use the wxWidgets library and, I can't use the latest version of TDM-GCC64 to create 32 bit windows with version 64 because the compiler always adds a default manifest ...

With version 5.1 of TDM-GCC64 everything works fine.

Thanks

**Comment by jmeubank** [comment]
I'm curious, what type of failure are you seeing and what version of Windows are you testing on?

I don't have a 32-bit Windows installation to work with at the moment, but I was under the impression that having a manifest compiled into the binary shouldn't cause any issues for older 32-bit versions of Windows.

Specifically for wxWidgets, you need to build with `CPP="cpp -m32"`, or the wxWidgets rcdefs.h will use preprocessor defines that include a 64-bit manifest. But as long as you get the correct values in rcdefs.h (`#define WX_CPU_X86`), wxWidgets 32-bit programs built with TDM-GCC-64 should work fine.

Sample wxWidgets build command:
```
mingw32-make -f makefile.gcc BUILD=release SHARED=1 UNICODE=1 CFLAGS="-m32" CXXFLAGS="-m32" LDFLAGS="-m32" CPP="cpp -m32" WINDRES="windres --use-temp-file -F pe-i386"
```

Sample manifest compiled into a wxWidgets exe:
```
sigcheck.exe -m calendar.exe

Sigcheck v2.80 - File version and signature viewer
Copyright (C) 2004-2020 Mark Russinovich
Sysinternals - www.sysinternals.com

<...>\calendar.exe:
        Verified:       Unsigned
        Link date:      1:48 PM 3/28/2021
        Publisher:      n/a
        Company:        n/a
        Description:    n/a
        Product:        n/a
        Prod version:   n/a
        File version:   n/a
        MachineType:    32-bit
        Manifest:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
<assemblyIdentity
    version="0.64.1.0"
    processorArchitecture="x86"
    name="Controls"
    type="win32"
/>
<description>wxWindows application</description>
<dependency>
    <dependentAssembly>
        <assemblyIdentity
            type="win32"
            name="Microsoft.Windows.Common-Controls"
            version="6.0.0.0"
            processorArchitecture="X86"
            publicKeyToken="6595b64144ccf1df"
            language="*"
        />
    </dependentAssembly>
</dependency>
</assembly>
```
